### ISSUE TITLE
Add focus-styles and design tokens for login-button-logo component

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-sdk#322]
Depends on #313

This will also require some backend changes to include meta-information about the logo (whether it's dark or light).

**Tasks**

- [x] Add design tokens `of.login-button-logo.dark.focus.border-color` and `of.login-button-logo.dark.focus.border-color`
- [ ] Implement CSS classname modifiers `openforms-login-button-logo--{dark|light}` depending on backend information (TODO!)
- [x] Add prop `appearance` with possible values `dark` and `light` to `LoginButtonIcon` component, which configures the modifier of the component
- [x] Add CSS styles that connect the classnames/modifiers to the appropriate design token
