### ISSUE TITLE
Prototyping: explore binding webcomponents via React (step 1)

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-sdk#345]
Part of the prototyping for a suitable formio renderer replacement architecture

The goal of this ticket is to explore rendering formio leaf nodes through a light binding with React (this means: exclude containers like repeating groups, columns, fieldsets..., which is part of step 2 if step 1 is viable).

The ideas to explore/validate here are:

* We can write a thin React wrapper around web components
* We can pass javascript state/properties/objects to web components
* We can hook into events fired by web components to update our internal React state

Formik can be left out of scope for this experiment, as bullet 3 fulfills the requirements (since it listens to `onChange`, `onBlur` etc. which are standard DOM events).

**Subtasks**

- [ ] Define a custom webcomponent for a date picker (`<proto-date-picker ... />`)
    - The component should just render three dropdowns: `day`, `month`, `year`
    - When any dropdown changes, the "value" of the component changes (which is an ISO-8601 date, `YYYY-MM-DD`)
    - Sample usage
      ```html
      <proto-date-picker name="myDate" value="2023-01-24" locale="nl" />
      ```
- [ ] Implement a React wrapper/higher order component
    - Sample code
      ```jsx
      const WebComponentWrapper = ({formioKey, values, component, onChange}) => {
        const currentValue = values?.[formioKey] || '';
        const ref = useRef(null);
        
        useEffect(
          () => {
            let mounted = false;
            if (!ref.current) return;
            mounted = true;
            // pass necessary context - this is our public API
            ref.current.ofValues = values;
            ref.current.formioComponent = component;
            // bind events
            ref.current.addEventListener('change', (event) => onChange(event));
            return () => {
              if (!mounted) return;
              ref.current.removeEventListener(...);
            };
          },
          [ref],
        );
        
        return (
          <proto-date-picker ref={ref} name={formioKey} value={currentValue} />
        );
      }
      ```
    - We use React refs & the `useEffect` hook to bind the relevant events _for our own functionality_)
    - The goal is to have the webcomponent-level events bubble up to our React components
    - We should be able to pass Javascript objects to the webcomponent itself, which can then use the full formio component options / full view of data to configure itself/re-render itself etc.
- [ ] Check that appropriate re-renders are triggered, e.g. by having a `nl`/`en` locale dropdown in the react state, which triggers a state/prop change and should be picked up by the webcomponent (arrange the date part dropdowns from day-month-year to month-day-year, for example,)

**Comment by svenvandescheur** [comment]
I have a few questions about this issue:

- What exactly is ment by "formio leaf nodes".
- It seems like most (not all) of the described behaviour is aleady implemented in [prototype 1 (wrappedelement.js)](https://github.com/open-formulieren/sdk-formik-prototype-1/blob/master/src/lib/react/wrappedelement.js)
  - Prototype 1 implements [wired-calendar](https://www.npmjs.com/package/wired-calendar) when specified by formio (backend) through a React wrapper, tracking change events and fowarding back to formik.
  - Can we extend this prototype for further research or do we want a fresh approach?

**Comment by sergei-maertens** [comment]
> What exactly is ment by "formio leaf nodes".

Components like textfield, date, textarea, password... The opposite of branch/container nodes like fieldset, columns...

> It seems like most (not all) of the described behaviour is aleady implemented

I am looking for a simpler implementation using React idioms and explicit event binding instead of the complexity of `syncTree`

> Can we extend this prototype for further research or do we want a fresh approach?

Fresh approach please - I want to break prototyping up in smaller, isolated parts and then chain individual aspects together to get to a full protoype. I believe we can achieve the set goals with a lot less code, and a lot less complex code, but to be able to fully commit to that, I need to see some ideas validated.

In this specific case, those ideas are:

* We can pass the necessary Javascript objects to webcomponents
* We can write a proper react "decorator" that is able to wrap webcomponents in a generic way
* We don't have to concern ourselves with DOM operations but only tap into the web component element events

This may lead to people wishing to use webcomponents (or alternatives) having to write small bits of react code which is okay as long as that React code is "react-tutorial limited to props" level.
