### ISSUE TITLE
Check if we can use PreserveData inside Form Summary components

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-sdk#632]
Follow up from the NL Design System monthly.

https://github.com/open-formulieren/open-forms-sdk/blob/0d43df295c37e5ac691b4fb55e390fa77aae47a7/src/components/FormStepSummary/index.js#L26

The `ComponentValueDisplay` is now used to render the form data in an appropriate format. There is some overlap with the [`PreserveData`](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-preserve-data--docs) component in the Utrecht community components, so we should investigate if we can make use of this component (and if not - figure out what is needed to make it work).

I suspect there may be some issues w/r to localization/internationalization.

**Tasks**

- [ ] Prototype using `PreserveData`
- [ ] If there's no limitations, apply it, otherwise:
- [ ] report back to upstream what causes adaptation problems
